return {
    CARD_BASE_SCALE = 2.5,
    CARD_DRAG_SCALE = 2.6,
    CARD_LERP_SPEED = 20,
    CARD_SCALE_LERP_SPEED = 32,
    CARD_SNAP_RADIUS = 100,
    CARD_WIDTH = 100,
    CARD_HEIGHT = 150,

    SLOT_SPACING = 20,

    DECK_CARDS = {
        { suit = "spades",   rank = "K",  class = "monster" },
        { suit = "spades",   rank = "Q",  class = "monster" },
        { suit = "spades",   rank = "J",  class = "monster" },
        { suit = "spades",   rank = "10", class = "monster" },
        { suit = "spades",   rank = "9",  class = "monster" },
        { suit = "spades",   rank = "8",  class = "monster" },
        { suit = "spades",   rank = "7",  class = "monster" },
        { suit = "spades",   rank = "6",  class = "monster" },
        { suit = "spades",   rank = "5",  class = "monster" },
        { suit = "spades",   rank = "4",  class = "monster" },
        { suit = "spades",   rank = "3",  class = "monster" },
        { suit = "spades",   rank = "2",  class = "monster" },
        { suit = "spades",   rank = "A",  class = "monster" },
        { suit = "hearts",   rank = "K",  class = "heal" },
        { suit = "hearts",   rank = "Q",  class = "heal" },
        { suit = "hearts",   rank = "J",  class = "heal" },
        { suit = "hearts",   rank = "10", class = "heal" },
        { suit = "hearts",   rank = "9",  class = "heal" },
        { suit = "hearts",   rank = "8",  class = "heal" },
        { suit = "hearts",   rank = "7",  class = "heal" },
        { suit = "hearts",   rank = "6",  class = "heal" },
        { suit = "hearts",   rank = "5",  class = "heal" },
        { suit = "hearts",   rank = "4",  class = "heal" },
        { suit = "hearts",   rank = "3",  class = "heal" },
        { suit = "hearts",   rank = "2",  class = "heal" },
        { suit = "hearts",   rank = "A",  class = "heal" },
        { suit = "diamonds", rank = "K",  class = "weapon" },
        { suit = "diamonds", rank = "Q",  class = "weapon" },
        { suit = "diamonds", rank = "J",  class = "weapon" },
        { suit = "diamonds", rank = "10", class = "weapon" },
        { suit = "diamonds", rank = "9",  class = "weapon" },
        { suit = "diamonds", rank = "8",  class = "weapon" },
        { suit = "diamonds", rank = "7",  class = "weapon" },
        { suit = "diamonds", rank = "6",  class = "weapon" },
        { suit = "diamonds", rank = "5",  class = "weapon" },
        { suit = "diamonds", rank = "4",  class = "weapon" },
        { suit = "diamonds", rank = "3",  class = "weapon" },
        { suit = "diamonds", rank = "2",  class = "weapon" },
        { suit = "diamonds", rank = "A",  class = "weapon" },
        { suit = "clubs",    rank = "K",  class = "monster" },
        { suit = "clubs",    rank = "Q",  class = "monster" },
        { suit = "clubs",    rank = "J",  class = "monster" },
        { suit = "clubs",    rank = "10", class = "monster" },
        { suit = "clubs",    rank = "9",  class = "monster" },
        { suit = "clubs",    rank = "8",  class = "monster" },
        { suit = "clubs",    rank = "7",  class = "monster" },
        { suit = "clubs",    rank = "6",  class = "monster" },
        { suit = "clubs",    rank = "5",  class = "monster" },
        { suit = "clubs",    rank = "4",  class = "monster" },
        { suit = "clubs",    rank = "3",  class = "monster" },
        { suit = "clubs",    rank = "2",  class = "monster" },
        { suit = "clubs",    rank = "A",  class = "monster" },
    }

}
