return {
    -- player
    PLAYER_MAX_HP = 20,

    -- card
    CARD_BASE_SCALE = 2.5,
    CARD_DRAG_SCALE = 2.6,
    CARD_LERP_SPEED = 20,
    CARD_SCALE_LERP_SPEED = 32,
    CARD_SNAP_RADIUS = 100,
    CARD_WIDTH = 100,
    CARD_HEIGHT = 150,

    SLOT_SPACING = 20,

    DECK_CARDS = {
        { suit = "spades",   rank = "K",  class = "monster" },
        { suit = "spades",   rank = "Q",  class = "monster" },
        { suit = "spades",   rank = "J",  class = "monster" },
        { suit = "spades",   rank = "10", class = "monster" },
        { suit = "spades",   rank = "9",  class = "monster" },
        { suit = "spades",   rank = "8",  class = "monster" },
        { suit = "spades",   rank = "7",  class = "monster" },
        { suit = "spades",   rank = "6",  class = "monster" },
        { suit = "spades",   rank = "5",  class = "monster" },
        { suit = "spades",   rank = "4",  class = "monster" },
        { suit = "spades",   rank = "3",  class = "monster" },
        { suit = "spades",   rank = "2",  class = "monster" },
        { suit = "spades",   rank = "A",  class = "monster" },
        { suit = "hearts",   rank = "K",  class = "health" },
        { suit = "hearts",   rank = "Q",  class = "health" },
        { suit = "hearts",   rank = "J",  class = "health" },
        { suit = "hearts",   rank = "10", class = "health" },
        { suit = "hearts",   rank = "9",  class = "health" },
        { suit = "hearts",   rank = "8",  class = "health" },
        { suit = "hearts",   rank = "7",  class = "health" },
        { suit = "hearts",   rank = "6",  class = "health" },
        { suit = "hearts",   rank = "5",  class = "health" },
        { suit = "hearts",   rank = "4",  class = "health" },
        { suit = "hearts",   rank = "3",  class = "health" },
        { suit = "hearts",   rank = "2",  class = "health" },
        { suit = "hearts",   rank = "A",  class = "health" },
        { suit = "diamonds", rank = "K",  class = "weapon" },
        { suit = "diamonds", rank = "Q",  class = "weapon" },
        { suit = "diamonds", rank = "J",  class = "weapon" },
        { suit = "diamonds", rank = "10", class = "weapon" },
        { suit = "diamonds", rank = "9",  class = "weapon" },
        { suit = "diamonds", rank = "8",  class = "weapon" },
        { suit = "diamonds", rank = "7",  class = "weapon" },
        { suit = "diamonds", rank = "6",  class = "weapon" },
        { suit = "diamonds", rank = "5",  class = "weapon" },
        { suit = "diamonds", rank = "4",  class = "weapon" },
        { suit = "diamonds", rank = "3",  class = "weapon" },
        { suit = "diamonds", rank = "2",  class = "weapon" },
        { suit = "diamonds", rank = "A",  class = "weapon" },
        { suit = "clubs",    rank = "K",  class = "monster" },
        { suit = "clubs",    rank = "Q",  class = "monster" },
        { suit = "clubs",    rank = "J",  class = "monster" },
        { suit = "clubs",    rank = "10", class = "monster" },
        { suit = "clubs",    rank = "9",  class = "monster" },
        { suit = "clubs",    rank = "8",  class = "monster" },
        { suit = "clubs",    rank = "7",  class = "monster" },
        { suit = "clubs",    rank = "6",  class = "monster" },
        { suit = "clubs",    rank = "5",  class = "monster" },
        { suit = "clubs",    rank = "4",  class = "monster" },
        { suit = "clubs",    rank = "3",  class = "monster" },
        { suit = "clubs",    rank = "2",  class = "monster" },
        { suit = "clubs",    rank = "A",  class = "monster" },
    },

    SUITS = { SPADES = "spades", HEARTS = "hearts", CLUBS = "clubs", DIAMONDS = "diamonds" },
    RANKS = { "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A" },
    CLASSES = { MONSTER = "monster", HEALTH = "health", WEAPON = "weapon" },

    VALUE_MAP = {
        ["2"] = 2,
        ["3"] = 3,
        ["4"] = 4,
        ["5"] = 5,
        ["6"] = 6,
        ["7"] = 7,
        ["8"] = 8,
        ["9"] = 9,
        ["10"] = 10,
        ["J"] = 11,
        ["Q"] = 12,
        ["K"] = 13,
        ["A"] = 14,
    },

    -- button colors
    GREEN_COLOR = { 0.25, 0.75, 0.25 },
    GREEN_HOVER_COLOR = { 0.35, 0.85, 0.35 },
    RED_COLOR = { 0.75, 0.25, 0.25 },
    RED_HOVER_COLOR = { 0.85, 0.35, 0.35 },
    BLUE_COLOR = { 0.25, 0.25, 0.75 },
    BLUE_HOVER_COLOR = { 0.35, 0.35, 0.85 },
    YELLOW_COLOR = { 0.75, 0.75, 0.25 },
    YELLOW_HOVER_COLOR = { 0.85, 0.85, 0.35 },
    PURPLE_COLOR = { 0.5, 0.25, 0.5 },
    PURPLE_HOVER_COLOR = { 0.6, 0.35, 0.6 },
    WHITE_COLOR = { 1, 1, 1 },
}
